<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.cache.interceptor.CacheErrorHandlerTests" tests="9" skipped="0" failures="0" errors="0" timestamp="2020-05-31T09:41:26" hostname="PC-20191010VAVI" time="0.185">
  <properties/>
  <testcase name="clearFail" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.078"/>
  <testcase name="evictFail" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.014"/>
  <testcase name="getFailProperException" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.013"/>
  <testcase name="putFail" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.016"/>
  <testcase name="getFail" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.014"/>
  <testcase name="getAndPutFail" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.012"/>
  <testcase name="putFailProperException" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.013"/>
  <testcase name="evictFailProperException" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.013"/>
  <testcase name="clearFailProperException" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.012"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
